### ISSUE TITLE
SRI Validation

### ISSUE THREAD

**Issue by jkreyling** [NJOGIS/NJRoadEditor#13]
The LRS tool won't allow an LRS Type 2 for any SRI with anything other than an underscore in the ninth position.  There are exceptions to this rule such as Alternate routes and spurs.  See the complete list below with SRI examples.  This appears to only affect LRS Type 2.

Business (00000001B_)
Truck (00000001T_)
W (00000009W_)
Z (00000027Z_)
Connector (00000076C_)
M (00000095M_)
Upper (000000139U_)
Spur (00000444S_)
X (00000446X_)
Spur Z (00000506SZ)
Alternate (00000511A_)
Spur 1 (00000549S1)
Spur 2 (00000549S2)
1 (000005611_)
2 (000005612_)
3 (000005613_)
4 (000005614_)
D (02000S56D_)

**Comment by EdFarrell** [comment]
Changed the tool to allow any character in the 9th position and still check for the _ in the 10th position
